// Service to handle questions via Local API (Node.js + SQLite)

const API_URL = '/api/questions';

export const QuestionService = {
    getAll: async () => {
        try {
            const res = await fetch(API_URL);
            if (!res.ok) throw new Error('Failed to fetch questions');
            return await res.json();
        } catch (error) {
            console.error('Error fetching questions:', error);
            return [];
        }
    },

    saveAll: async (questions) => {
        try {
            // Ensure format matches API expectation
            const formatted = questions.map(q => ({
                question: q.question,
                tags: q.tags,
                answers: q.answers,
                // id will be generated by backend if missing
            }));

            const res = await fetch(API_URL, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(formatted)
            });

            if (!res.ok) throw new Error('Failed to save questions');

            return await res.json();
        } catch (error) {
            console.error('Error saving questions:', error);
            throw error;
        }
    },

    getQuestionsByTag: async (tag) => {
        try {
            // Fetch all and filter client-side for now (Simpler backend)
            // Or typically: fetch(`${API_URL}?tag=${tag}`)
            const all = await QuestionService.getAll();
            return all.filter(q => q.tags && q.tags.includes(tag));
        } catch (error) {
            console.error('Error fetching by tag:', error);
            return [];
        }
    },

    deleteQuestion: async (id) => {
        try {
            const res = await fetch(`${API_URL}/${id}`, {
                method: 'DELETE'
            });
            if (!res.ok) throw new Error('Failed to delete question');
            return true;
        } catch (error) {
            console.error('Error deleting question:', error);
            throw error;
        }
    },

    updateQuestion: async (id, question) => {
        try {
            const res = await fetch(`${API_URL}/${id}`, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(question)
            });
            if (!res.ok) throw new Error('Failed to update question');
            return true;
        } catch (error) {
            console.error('Error updating question:', error);
            throw error;
        }
    }
};
